apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - name: {{ .Values.labels.app }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: "{{ .Values.resources.limits.memory }}"  # Ensure this is enclosed in double quotes
            cpu: "{{ .Values.resources.limits.cpu }}"        # Ensure this is enclosed in double quotes
          requests:
            memory: "{{ .Values.resources.requests.memory }}"  # Ensure this is enclosed in double quotes
            cpu: "{{ .Values.resources.requests.cpu }}"        # Ensure this is enclosed in double quotes
        ports:
        - containerPort: {{ .Values.service.targetPort }}